### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MahmudQasem** [AzAgarampur/byeintegrity3-uac#1]
SystemSettings.Handlers.dll!UserAssocSet->"Internal" not found.

**Comment by AzAgarampur** [comment]
It seems like you're running this on Windows 10

What build are you running it on?

**Comment by AzAgarampur** [comment]
I think you are running it on a Windows 10 build other than 19041/19042. This will only work on those Windows 10 builds because `SystemSettings.Handlers.dll!UserAssocSet->"Internal"` is only present on those versions. Otherwise this won't work on earlier versions of Windows 10.

If you want something that'll work, use UACMe. I'm closing this issue due to no response.
